apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: spring-petclinic-workload
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "false"
  name: spring-petclinic-workload
  namespace: mydev-ns
spec:
  source:
    git:
      ref:
        branch: accelerator
      url: https://github.com/dkhopade/spring-petclinic
